[package]
name = "jsonpath_lua"
version = "0.1.0"
authors = ["Changseok Han <freestrings@gmail.com>"]
license = "MIT"
description = "This `lua` module will be deprecated since 4.0."
[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = { version = "1.0", features = ["preserve_order"] }
jsonpath_lib = { path = "../" }

[[bin]]
name = "bench"
path = "bench_lua_vs_rust/example.rs"

